* Introduction

  =Feedback Portal= is an application that allows the users of Virtual
  Labs to post their feedback about a lab or an experiment.  The
  portal has a fixed set of questions and the feedback is saved in the
  database using =dataservice=.  This feedback can be used later for
  improving a particular lab or an experiment.

  Note: This document is work in progress.

* Requirements

  1. A front-end(UI) that displays relevant questions about a lab, an
     experiment or Virtual Labs in general.
  2. An API to integrate this portal with =dataservice=.
     
* Design & Implementation

  The feedback form will be available from three different places(levels - lab
  level, experiment level and directly from =feedback.vlabs.ac.in=). The IP of
  the user is detected at the backend and is not part of the questionnaire.

** The UI
   
   The UI or the feedback form consists of fixed set of questions so that it is
   easier for a user to assess a lab/experiment. The UI is as follows,
   depending on the place from where the request has originated :

 1) *Generic Feedback Form*
    
    This is the form that can be directly accessed from
    =feedback.vlabs.ac.in=. This form is also served if the request comes from
    the =vlabs= landing page. Following is the questionnaire for this form -

   + Name

     Name of the user submitting feedback.
   
   + Email

     Email address of the user.

   + Type Of User

     Type of the user like faculty or student.
  
   + How useful do you think Virtual Labs is for an engineering student ?

   + What are your suggestions about making Virtual Labs better ? 


 2) *Experiment Specific Feedback Form* 

    This feedback form can be rendered from any experiment of a lab. Questions
    asked are:

   + Name

   + Email

   + Type Of User

   + What is the name of your institute ?

   + Lab Name

     Lab name refers to the lab about which the feedback is being given. This
     is a pre-populated field.
 
   + Experiment Name

     Experiment name refers to the experiment about which the feedback is being
     given. This is a pre-populated field.

   + What is your feedback about the experiment ?

   + What are your suggestions about making the experiment better ?


 3) *Lab Specific Feedback Form*

    Feedback form rendered from a lab has following questions:

   + Name

   + Email

   + Type Of User

   + What is the name of your institute ?

   + Lab Name

     This is a pre-populated field.

   + What is your feedback about the lab ?

   + What are your suggestions about making the lab better ?


** Integration with =dataservice=

   The feedback portal makes REST API calls to =dataservice= for
   submitting the feedback data.   
       
   [[https://github.com/vlead/feedback-portal/blob/develop/app.py][Link to app.py]]

* Releases

** v0.1.0
  
   This release contains the feedback portal, with new UI, and
   integration with data service.
