#+TITLE: Building a Feedback Portal :  Ground up to the Cloud
#+AUTHOR: VLEAD
#+DATE: [2016-08-15 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Version/Branch History

* Application
  The outreach portal helps conduct workshops on Virtual Labs.  The development
  of the application is divided into the following phases:

** [[./requirements/index.org][Requirements]]

** Design
*** Application Programming Interface
:PROPERTIES:
:CUSTOM_ID: api
:END: 
    1. Display the feedback form. 
   
       - URL :: /feedback?lab_name=:lab_name&exp_name=:exp_name&key=:key
                OR
                /feedback?lab_name=:lab_name&key=:key

       - Method :: GET

       - URL Params
         Required: lab_name=[string], key=[string]
         Optional: exp_name=[string]

       - Success Response
         + Code: 200

         + Content:
           {
            lab_name: 'lab_name',
            exp_name: 'exp_name',
            questions: [{name: 'question', 
                         type: 'radio | checkbox | textbox',
                         options: 'list of options' | 'size of text'}, ....]
           }

       - Error Response:
         + Code: 401 UNAUTHORIZED

         + Content: { error : "Wrong Key configured" }

         OR

         + Code: 400 Bad Request

         + Content: { error : "lab name is mandatory and experiment is optional" }

    2. Save the feedback form. 
       The authentication for the =POST= is sent as part of header.
       - URL :: /feedback

       - Method :: POST

       - Data Params
         {
            lab_name: 'lab_name',
            exp_name: 'exp_name',
            questions: [{name: 'question', 
                         answers: [ans1, ...]
           }

       - Success Response
         + Code: 200

         + Content:
           {
             status: "success"
           }

       - Error Response:
         + Code: 401 UNAUTHORIZED

         + Content: { error : "Wrong Key configured" }

         OR

         + Code: 400 Bad Request

         + Content: { error : "some of the parameters are not part of the
           request" }

    3. Display the feedback form. 
   
       - URL :: /feedback_usage_by_workshop?ip=:ip&date=:date&key=:key

       - Method :: GET

       - URL Params
         Required: ip=[string]
                   date=[string], the format of the date string is in
         'mm-dd-yyyy' format. 
                   key=[string]
                  
       - Success Response
         + Code: 200

         + Content:
           {
            usage: 'usage_number'
           }

       - Error Response:
         + Code: 401 UNAUTHORIZED

         + Content: { error : "Wrong Key configured" }

         OR

         + Code: 400 Bad Request

         + Content: { error : "IP and Date are mandatory and date should be in
           'mm-dd-yyyy' format" }

    4. Display the feedback form. 
   
       - URL :: /feedback_dump?date=:date&key=:key

       - Method :: GET

       - URL Params
         Required: date=[string], the format of the string is in 'mm-dd-yyyy'
         format
                   key=[string]

       - Success Response
         + Code: 200

         + Content:
           {
            feedbacks: [{lab_name: 'lab_name',
                         exp_name: 'exp_name',
                         date: 'mm-dd-yyyy',
                         IP: 'ip',
                         responses: [{question: 'name',
                                      answers: ['val1',..]
                                     }, ...]
                        }, ...]
           }

       - Error Response:
         + Code: 401 UNAUTHORIZED

         + Content: { error : "Wrong Key configured" }

         OR

         + Code: 400 Bad Request

         + Content: { error : "Date is mandatory and should be in 'mm-dd-yyyy' format" }


*** Services Interplay
    The following diagram summarizes the interplay of different services that
    enable collection of feedback and integration with =virtual labs= and
    =outreach portal=.

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/1h7Tqof8X9u_V3qKAs8Yu6Jk9VzxjIzDz78FynwGYCVk/pub?w=960&amp;h=720">
<p align="center"> Services Interplay </p>
#+END_HTML

  To edit the feedback relations image click [[https://docs.google.com/drawings/d/1h7Tqof8X9u_V3qKAs8Yu6Jk9VzxjIzDz78FynwGYCVk/edit?usp=sharing][here]]


*** Capturing workshop usage through feedback forms
    Feebback forms are submitted by the students attending a workshop after
    completion of each experiment.  Outreach facilitates conducting of
    workshops.   The scenario below shows the way to capture the usage from the
    feedback forms submitted for a workshop.

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/1bWGDP8jT7JUW49D0Wp7bI9uzqfZ8XGPWkCti7jqg17M/pub?w=960&amp;h=720">
<p align="center"> Workshop Usage </p>
#+END_HTML


    To edit the feedback relations image click [[https://docs.google.com/drawings/d/1bWGDP8jT7JUW49D0Wp7bI9uzqfZ8XGPWkCti7jqg17M/edit?usp=sharing][here]]


*** Dynamic generation of =feedback form=
    Feebback form is buult on the browser from the data that is sent as part of
    the [[./index.org::#api][=GET=]] response.  The response contains all the relevant data to build
    the form.  It will hold the questions, the type like if the question is a
    radio button or a check box etc. and the values for each option. 

#+BEGIN_HTML
<img src="https://docs.google.com/drawings/d/10nfQZtJ7NJaDYKZru5DiXlS-YZaXQ1nlLoYb5-oRaCY/pub?w=960&amp;h=720">
<p align="center"> Workshop Usage </p>
#+END_HTML


    To edit the feedback relations image click [[https://docs.google.com/drawings/d/10nfQZtJ7NJaDYKZru5DiXlS-YZaXQ1nlLoYb5-oRaCY/edit?usp=sharing][here]]
    

*** Dumping the data from the feedback service to elastic search
    

** [[./data-model/index.org][Data Model]]

** [[./runtime/index.org][Runtime]]

** [[./deployment/index.org][Deployment]]
       

* Tangle                                       :boilerplate:
#+BEGIN_SRC python :eval no :tangle __init__.py
print "outreach package"
#+END_SRC
